# RF-KID-001 Pediatric Kidney Candidate Patterns

## Context

This table is **candidate-grade synthesis** for `kidney_suite_v1`, not verified rule text. I treated the attached RF-KID-001 bundle as prior context, prioritized independently retrievable open or freely distributed sources where possible, and explicitly preserved thresholds that remain paywalled or rights-restricted instead of backfilling them from memory. The existing bundle is marked `reviewedThrough: 2026-07-22`. fileciteturn2file0

Most of the hardest numerics can be grounded from accessible material: CKiD/Schwartz eGFR equations are available through PubMed/PMC, KDIGO CKD and AKI materials are freely distributed or openly reproduced in authoritative nephrology sources, pediatric hematuria/proteinuria thresholds are available in a PMC-readable review, and AAP 2017 pediatric BP thresholds are reproducible from an open AAFP summary that explicitly reprints the AAP table. The main remaining paywalled numerics are the **spot UPCR thresholds stated in `mg/mmol`** from the Kaminska review and the original AAP/Pediatrics and Pediatrics in Review publisher pages. citeturn13search2turn29view0turn24search2turn25view0turn38search0turn27view1turn37search1

## Assumptions

I preserved **source-native units** rather than silently converting, especially where pediatric and adult conventions diverge. Where a source set presents both `mg/mg` and `mg/mmol`, both are retained. Where a source could support a qualitative branch but not a defensible number, the threshold cell is marked **`NO CITATION — do not use`** rather than inferring a cutoff. citeturn38search0turn34search0turn33search0turn23search0

For AAP blood-pressure categories, the original 2017 guideline is still the governing source, but the most independently retrievable numeric table in this research pass is the 2018 AAFP review that reproduces AAP Table 1 and cites the original AAP guideline. I therefore cite both the **AAP DOI as source-of-record** and the **AAFP table as open retrieval path**. citeturn27view1turn11search4

## Approach

I organized the module patterns around the requested coverage areas: hematuria branching, AKI staging, CKD stage-transition logic, pediatric hypertension, and electrolyte overlaps that a kidney module may need to surface without double-owning CMP logic. Rows are written as **downstream converter candidates**, so many rows are deliberately narrow and preserve coexistence of competing thresholds rather than reconciling them. fileciteturn2file1

Where the RF-KID-001 evidence bundle already held a threshold from a primary or review source but the same number was not cleanly extractable from an open passage in this session, I retained the number **only when the bundle already captured it** and flagged the access status honestly. This mainly affects the **CKiD U25 coefficient constants** and the **paywalled `mg/mmol` UPCR thresholds**. fileciteturn2file0

## Candidate pattern table

| Candidate pattern (condition) | Population / age band | Trigger (the observable/derived fact) | Threshold value | UCUM unit | Direction (≥ / ≤ / range) | Intended output (interpretive note / flag / scope-exit / referral-readiness) | Source (title + DOI/URL + year) | Access (open / paywalled) | Conflicts-with (other cutoff to preserve, if any) |
|---|---|---|---|---|---|---|---|---|---|
| U25 creatinine eGFR equation | Children/young adults age 1–25 y | Height, serum creatinine, sex available; creatinine-based eGFR needed | `eGFR = K × [height (m)/SCr (mg/dL)]`; male `K = 41.8` | `mL/min/1.73 m2` | `=` | interpretive note | *Age- and sex-dependent clinical equations to estimate glomerular filtration rates in children and young adults with chronic kidney disease* `doi:10.1016/j.kint.2020.10.047` (2021); coefficient captured in RF-KID-001 bundle; PubMed lists PMCID `PMC9083470`. fileciteturn2file0 citeturn13search2 | Open via PMC author manuscript | Preserve separately from bedside Schwartz `0.413 × height/SCr` |
| U25 creatinine eGFR equation | Children/young adults age 1–25 y | Height, serum creatinine, sex available; creatinine-based eGFR needed | `eGFR = K × [height (m)/SCr (mg/dL)]`; female `K = 37.6` | `mL/min/1.73 m2` | `=` | interpretive note | Same Pierce 2021 source and bundle capture. fileciteturn2file0 citeturn13search2 | Open via PMC author manuscript | Preserve separately from bedside Schwartz `0.413 × height/SCr` |
| U25 age-dependent creatinine coefficient band | Male age 1–25 y | Age-dependent creatinine U25 variant selected | Male age-dependent `K` rises from `35.7` at age 1 to `50.8` at age ≥18 | `mL/min/1.73 m2` | `range` | interpretive note | Pierce 2021 `doi:10.1016/j.kint.2020.10.047`; coefficient band captured in RF-KID-001 bundle. fileciteturn2file0 citeturn13search2 | Open via PMC author manuscript | Preserve separately from sex-only constant `41.8` |
| U25 age-dependent creatinine coefficient band | Female age 1–25 y | Age-dependent creatinine U25 variant selected | Female age-dependent `K` rises from `33.1` at age 1 to `41.4` at age ≥18 | `mL/min/1.73 m2` | `range` | interpretive note | Pierce 2021 `doi:10.1016/j.kint.2020.10.047`; coefficient band captured in RF-KID-001 bundle. fileciteturn2file0 citeturn13search2 | Open via PMC author manuscript | Preserve separately from sex-only constant `37.6` |
| U25 cystatin-C eGFR equation | Children/young adults age 1–25 y | Cystatin C, sex available; cystatin-C-based eGFR needed | `eGFR = K × (1/cystatin C)`; male `K = 81.9` | `mL/min/1.73 m2` | `=` | interpretive note | Pierce 2021 `doi:10.1016/j.kint.2020.10.047`; coefficient captured in RF-KID-001 bundle. fileciteturn2file0 citeturn13search2 | Open via PMC author manuscript | Preserve separately from creatinine-based U25 and bedside Schwartz |
| U25 cystatin-C eGFR equation | Children/young adults age 1–25 y | Cystatin C, sex available; cystatin-C-based eGFR needed | `eGFR = K × (1/cystatin C)`; female `K = 74.9` | `mL/min/1.73 m2` | `=` | interpretive note | Pierce 2021 `doi:10.1016/j.kint.2020.10.047`; coefficient captured in RF-KID-001 bundle. fileciteturn2file0 citeturn13search2 | Open via PMC author manuscript | Preserve separately from creatinine-based U25 and bedside Schwartz |
| Bedside Schwartz creatinine eGFR equation | Children age 1–16 y in original derivation; often used more broadly in pediatrics | Height and serum creatinine available; simplified creatinine eGFR needed | `eGFR = 0.413 × [height (cm)/SCr (mg/dL)]` | `mL/min/1.73 m2` | `=` | interpretive note | *New Equations to Estimate GFR in Children with CKD* `doi:10.1681/ASN.2008030287` (2009); PMC states bedside calculation `0.413*(height/serum creatinine)`. citeturn29view0 | Open via PMC | Preserve separately from U25 age/sex-dependent coefficients |
| Microscopic hematuria definition | Children/adolescents | Spun urine microscopy positive on repeated checks | `>5` | `RBC/HPF` | `>` | flag | *Hematuria and Proteinuria in Children* `doi:10.1542/pir.2017-0300` (2018); PMC-readable copy states microscopic hematuria as `>5 RBCs/HPF` on 2–3 occasions. citeturn38search0 | Open via PMC author manuscript | Preserve alongside uncentrifuged threshold `>5 RBC/mm3` |
| Microscopic hematuria definition | Children/adolescents | Uncentrifuged urine microscopy positive on repeated checks | `>5` | `RBC/mm3` | `>` | flag | Same 2018 review/PMC copy. citeturn38search0 | Open via PMC author manuscript | Preserve alongside centrifuged threshold `>5 RBC/HPF` |
| Persistent microscopic hematuria | Children/adolescents | Positive urinalyses continue beyond transient window | `>4–6 weeks` **and** `>5 RBC/HPF` absent exercise, menses, trauma | `weeks`; `RBC/HPF` | `>` | flag | Same 2018 review/PMC copy defines persistent hematuria as more than 4–6 weeks with more than 5 RBC/HPF. citeturn38search0 | Open via PMC author manuscript | Preserve separately from isolated single-episode microscopic hematuria |
| Glomerular hematuria branch | Children/adolescents | Dysmorphic RBCs, acanthocytes, or RBC casts seen on urine microscopy | `NO CITATION — do not use` | `NA` | `present` | interpretive note | *Approach to Persistent Microscopic Hematuria in Children* `doi:10.34067/KID.0003222020` (2020); figure description states RBC casts and dysmorphic RBCs are consistent with a glomerular source, but no validated numeric cutoff was retrieved. citeturn35search0 | Open access | Preserve separately from nonglomerular morphology cues |
| Nonglomerular hematuria branch | Children/adolescents | Isomorphic/eumorphic RBCs or bright-red/clotty lower-tract pattern | `NO CITATION — do not use` | `NA` | `present` | interpretive note | LA AAP clinician summary citing pediatric nephrology references describes normal RBC morphology for nonglomerular sources, but no retrievable numeric cutoff was found. `https://www.laaap.org/hematuria-and-proteinuria-in-children` (2026). citeturn37search2 | Open web educational summary | Preserve separately from glomerular morphology cues |
| Hypercalciuria branch for nonglomerular hematuria | Children age >2 y | Urine calcium/creatinine ratio available | `>0.2` | `mg/mg` | `>` | interpretive note | 2018 hematuria/proteinuria review via PMC defines hypercalciuria in children >2 y as urine Ca/Cr `>0.2 mg/mg`. citeturn38search0 | Open via PMC author manuscript | Preserve infant-specific higher acceptable upper limits |
| Infant Ca/Cr upper limit | Infants <6 months | Urine calcium/creatinine ratio available | `<0.8` acceptable upper limit | `mg/mg` | `<` | interpretive note | Same 2018 review/PMC copy. citeturn38search0 | Open via PMC author manuscript | Preserve separately from >2 y threshold `>0.2 mg/mg` |
| Infant Ca/Cr upper limit | Infants 6–12 months | Urine calcium/creatinine ratio available | `<0.6` acceptable upper limit | `mg/mg` | `<` | interpretive note | Same 2018 review/PMC copy. citeturn38search0 | Open via PMC author manuscript | Preserve separately from >2 y threshold `>0.2 mg/mg` |
| Pediatric proteinuria by spot ratio | Children >24 months | Spot first-morning or random UPCR available | `>0.2` | `mg/mg` | `>` | flag | *Proteinuria in Children: Evaluation and Differential Diagnosis* `https://www.aafp.org/afp/2017/0215/p248` (2017) states UPr/Cr `>0.2` warrants further evaluation. citeturn34search0 | Open / freely accessible review | Preserve separately from infant cutoff `>0.5 mg/mg` |
| Infant proteinuria by spot ratio | Children 6–24 months | Spot UPCR available | `>0.5` | `mg/mg` | `>` | flag | Same AAFP 2017 review states `>0.5` for ages 6–24 months is abnormal. citeturn34search0 | Open / freely accessible review | Preserve separately from older-child cutoff `>0.2 mg/mg` |
| Orthostatic proteinuria pattern | Children/adolescents | First-morning UPCR and later upright/random UPCR both available | First-morning `≤0.2` **and** upright/random `>0.2` | `mg/mg` | `range` | interpretive note | AAFP 2017 review defines orthostatic proteinuria this way. citeturn34search0 | Open / freely accessible review | Preserve separately from persistent proteinuria |
| Proteinuria by 24-hour quantitation | Children | Quantified urine protein excretion available | `>100` | `mg/m2/day` | `>` | flag | AAFP 2017 review states normal protein excretion is `<100 mg/m2/day`. citeturn34search0 | Open / freely accessible review | Preserve separately from nephrotic-range threshold `>1000 mg/m2/day` |
| Pediatric nephrotic-range proteinuria by spot ratio | Children | Spot UPCR available | `>2` | `mg/mg` | `>` | referral-readiness | AAFP 2017 review and Schwartz 2009 PMC both state nephrotic-range proteinuria at UPr/Cr `>2`. citeturn34search0turn29view0 | Open / freely accessible review | **Do not reconcile** with paywalled `>350 mg/mmol` threshold |
| Pediatric nephrotic-range proteinuria by 24-hour quantitation | Children | Quantified urine protein excretion available | `>1000` | `mg/m2/day` | `>` | referral-readiness | AAFP 2017 review defines nephrotic syndrome/heavy proteinuria as `>1000 mg/m2/day`. citeturn34search0 | Open / freely accessible review | Preserve separately from spot-ratio thresholds |
| Spot UPCR proteinuria threshold in SI units | General laboratory / mixed populations; not pediatric-specific | Spot UPCR reported in SI units | `>20` | `mg/mmol` | `>` | interpretive note | *Diagnostic utility of protein to creatinine ratio (P/C ratio) in spot urine sample within routine clinical practice* `doi:10.1080/10408363.2020.1723487` (2020); threshold captured in RF-KID-001 bundle; source itself remains paywalled. fileciteturn2file0 | Paywalled | Preserve separately from pediatric `>0.2 mg/mg` |
| Spot UPCR nephrotic threshold in SI units | General laboratory / mixed populations; not pediatric-specific | Spot UPCR reported in SI units | `>350` | `mg/mmol` | `>` | interpretive note | Same Kaminska 2020 review; threshold captured in RF-KID-001 bundle; paywalled source. fileciteturn2file0 | Paywalled | **Conflicts with** pediatric nephrotic threshold `>2 mg/mg` |
| Hematuria plus proteinuria referral red flag | Children/adolescents | Microscopic or gross hematuria coexists with abnormal proteinuria | Hematuria **plus** UPCR `>0.2` (`>0.5` if 6–24 months) | `mg/mg` | `>` | referral-readiness | AAFP 2017 review states coexisting hematuria raises concern for clinically significant renal disease; UPCR abnormality thresholds from same review. citeturn34search0 | Open / freely accessible review | Preserve age-specific infant cutoff |
| KDIGO AKI stage 1 | Children/adolescents | AKI staging using creatinine and/or urine output | SCr `1.5–1.9 × baseline` **or** absolute SCr increase `≥0.3 mg/dL` within 48 h **or** urine output `<0.5 mL/kg/h` for `6–12 h` | `mg/dL`; `mL/kg/h`; `hours` | `range` | flag | *Incorrect application of the KDIGO acute kidney injury staging criteria* `doi:10.1093/ckj/sfab256` (2022) reproduces KDIGO staging table; KDIGO states guidelines are freely accessible. citeturn25view0turn24search2 | Open access / freely distributed guideline basis | Preserve separately from pRIFLE Risk |
| KDIGO AKI stage 2 | Children/adolescents | AKI staging using creatinine and/or urine output | SCr `2.0–2.9 × baseline` **or** urine output `<0.5 mL/kg/h` for `≥12 h` | `mL/kg/h`; `hours` | `range` | flag | Same CKJ 2022 open article reproducing KDIGO table. citeturn25view0turn24search2 | Open access / freely distributed guideline basis | Preserve separately from pRIFLE Injury |
| KDIGO AKI stage 3 | Children/adolescents | AKI staging using creatinine, urine output, RRT, and pediatric eGFR criterion | SCr `≥3.0 × baseline` **or** SCr `≥4.0 mg/dL` **or** initiation of renal replacement therapy **or** in patients `<18 y`, eGFR `<35 mL/min/1.73 m2` **or** urine output `<0.3 mL/kg/h` for `≥24 h` **or** anuria for `≥12 h` | `mg/dL`; `mL/min/1.73 m2`; `mL/kg/h`; `hours` | `range` | referral-readiness | Same CKJ 2022 open article reproducing KDIGO table, including the pediatric `<18 y` eGFR criterion. citeturn25view0turn24search2 | Open access / freely distributed guideline basis | Preserve separately from pRIFLE Failure |
| pRIFLE Risk | Children/adolescents | Pediatric RIFLE staging by estimated creatinine clearance and/or urine output | eCCl decrease by `25%` **or** urine output `<0.5 mL/kg/h` for `8 h` | `%`; `mL/kg/h`; `hours` | `range` | flag | NHSGGC pediatric acute renal failure guideline, last reviewed 2020, gives pRIFLE table. `https://www.clinicalguidelines.scot.nhs.uk/ggc-paediatric-guidelines/ggc-paediatric-guidelines/kidney-diseases/acute-renal-failure-management-and-investigation-paediatrics-353/` (2020). citeturn18view1turn22view0 | Open institutional guideline | Preserve separately from KDIGO stage 1 |
| pRIFLE Injury | Children/adolescents | Pediatric RIFLE staging by estimated creatinine clearance and/or urine output | eCCl decrease by `50%` **or** urine output `<0.5 mL/kg/h` for `16 h` | `%`; `mL/kg/h`; `hours` | `range` | flag | Same NHSGGC 2020 pediatric guideline. citeturn18view1turn22view0 | Open institutional guideline | Preserve separately from KDIGO stage 2 |
| pRIFLE Failure | Children/adolescents | Pediatric RIFLE staging by estimated creatinine clearance and/or urine output | eCCl decrease by `75%` **or** eCCl `<35 mL/min/1.73 m2` **or** urine output `<0.3 mL/kg/h` for `24 h` **or** anuric for `12 h` | `%`; `mL/min/1.73 m2`; `mL/kg/h`; `hours` | `range` | referral-readiness | Same NHSGGC 2020 pediatric guideline. citeturn18view1turn22view0 | Open institutional guideline | Preserve separately from KDIGO stage 3 |
| CKD chronicity criterion | Children/adolescents | Kidney abnormality persists beyond acute/transient window | `≥3 months` | `months` | `≥` | interpretive note | KDIGO 2024 commentary and secondary summaries restate KDIGO definition as abnormalities of kidney structure or function present for a minimum of 3 months. citeturn32search3turn32search6 | Open access commentary / open review | Preserve separately from pediatric “low eGFR” screening flag |
| Pediatric low-eGFR screening flag | Children/adolescents age >2 y | eGFRcr available | `<90` | `mL/min/1.73 m2` | `<` | flag | KDIGO 2024 pediatric commentary states eGFR below 90 can be flagged as low in children/adolescents >2 y; official KDIGO pediatric takeaways page is freely distributed. citeturn31view1turn28search1 | Freely distributed guideline commentary | **Do not collapse** into chronic CKD threshold `<60 for ≥3 months` |
| CKD diagnosis/referral GFR threshold | Children/adolescents | Reduced GFR persists long enough to satisfy CKD criterion | `<60` for `≥3 months` | `mL/min/1.73 m2`; `months` | `<` and `≥` | referral-readiness | KDIGO-based summaries restate decreased GFR `<60` present for at least 3 months as a diagnostic CKD criterion. citeturn32search1turn32search3 | Open secondary summaries of KDIGO | **Do not collapse** into pediatric low-eGFR flag `<90` |
| KDIGO GFR category map | Children/adolescents | CKD G-category classification required | `G1 ≥90; G2 60–89; G3a 45–59; G3b 30–44; G4 15–29; G5 <15` | `mL/min/1.73 m2` | `range` | interpretive note | KDIGO-aligned heatmap and summaries reproduce G1–G5 boundaries. citeturn33search0turn32search5 | Freely distributed KDIGO companion resource / mirror of official figure | Preserve separately from pediatric low-eGFR screening flag |
| KDIGO albuminuria category map | Children/adolescents | UACR category classification required | `A1 <30 mg/g and <3 mg/mmol; A2 30–300 mg/g and 3–30 mg/mmol; A3 >300 mg/g and >30 mg/mmol` | `mg/g`; `mg/mmol` | `range` | interpretive note | KDIGO 2024 bundle capture plus KDIGO-aligned heatmap reproduce A1–A3 boundaries; mg/mmol equivalents retained as captured in RF-KID-001 bundle. fileciteturn2file0 citeturn33search0 | Freely distributed companion resource; bundle-captured equivalents | Preserve separately from total-protein UPCR thresholds |
| AAP BP classification map for children | Age 1 to <13 y | Office BP classification needed | `Normal <90th percentile; Elevated ≥90th to <95th percentile or 120/80 mmHg to <95th percentile, whichever is lower; Stage 1 ≥95th percentile to <95th percentile + 12 mmHg, or 130/80 to 139/89 mmHg, whichever is lower; Stage 2 ≥95th percentile + 12 mmHg, or ≥140/90 mmHg, whichever is lower` | `percentile`; `mmHg` | `range` | flag | AAFP 2018 reproduces AAP 2017 Table 1 and cites original AAP guideline `doi:10.1542/peds.2017-1904`. citeturn27view1turn11search4 | Original source paywalled; open secondary summary available | Preserve separately from age ≥13 static cut points |
| AAP BP classification map for adolescents | Age ≥13 y | Office BP classification needed | `Normal <120/<80; Elevated 120/<80 to 129/<80; Stage 1 130/80 to 139/89; Stage 2 ≥140/90` | `mmHg` | `range` | flag | Same AAFP 2018 table reproducing AAP 2017 categories. citeturn27view1turn11search4 | Original source paywalled; open secondary summary available | Preserve separately from age 1–<13 percentile-based scheme |
| Electrolyte overlap: hyperkalemia action threshold | Children with suspected AKI/acute renal failure | Serum potassium available | `>6.0` on `2` separate occasions | `mmol/L` | `>` | flag | NHSGGC pediatric acute renal failure guideline definition includes hyperkalaemia `K >6.0 mmol/L on 2 separate occasions`; last reviewed 2020. citeturn18view0turn22view0 | Open institutional guideline | CMP ownership overlap; do not double-own silently |
| Electrolyte overlap: hyponatremia consultation threshold | Children | Serum sodium available | `<130` or symptomatic | `mmol/L` | `<` | flag | RCH Melbourne hyponatraemia guideline recommends consultation when sodium `<130 mmol/L`; last updated November 2023. `https://www.rch.org.au/clinicalguide/guideline_index/hyponatraemia/` citeturn18view3turn17view1 | Open institutional guideline | CMP ownership overlap; preserve stricter transfer threshold `<125` |
| Electrolyte overlap: hyponatremia transfer threshold | Children | Serum sodium available | `<125` | `mmol/L` | `<` | referral-readiness | Same RCH guideline recommends transfer when sodium `<125 mmol/L`. citeturn18view3turn17view1 | Open institutional guideline | CMP ownership overlap; preserve softer consult threshold `<130` |
| Electrolyte overlap: CKD metabolic acidosis threshold | Children age >2 y with CKD | Serum total CO₂ / bicarbonate available | maintain `≥22`; therefore low if `<22` | `mmol/L` | `<` | flag | NKF KDOQI pediatric CKD guideline states serum total CO₂ should be maintained at `≥22 mmol/L` in patients >2 y. `https://kidneyfoundation.cachefly.net/professionals/KDOQI/guidelines_pedbone/guide16.htm` citeturn23search0 | Freely accessible guideline | CMP ownership overlap; preserve age <2 lower threshold |
| Electrolyte overlap: CKD metabolic acidosis threshold | Neonates/young infants <2 y with CKD | Serum total CO₂ / bicarbonate available | maintain `≥20`; therefore low if `<20` | `mmol/L` | `<` | flag | Same KDOQI pediatric guideline sets lower target `≥20 mmol/L` for neonates/young infants below age 2. citeturn23search0 | Freely accessible guideline | CMP ownership overlap; preserve age >2 threshold `<22` |

## Candidate-without-threshold patterns and conflicts

Patterns that were found but could **not** be grounded to a citable number should still be retained as candidates for later verification. The most important are the **glomerular versus nonglomerular morphology branches** based on dysmorphic RBCs/acanthocytes, RBC casts, or isomorphic RBCs; several pediatric reviews and educational summaries treat these as major branch points, but I did **not** retrieve a stable pediatric **numeric proportion cutoff** for dysmorphic cells that was suitable for a threshold cell in this pass. citeturn35search0turn37search2

The same is true for several **hematuria referral cues**: edema, cola-colored urine, flank pain, recurrent gross hematuria, recent streptococcal infection, family history of chronic kidney disease or hearing loss, and extrarenal syndromic features. They are clinically important cause-directed cues, but I did not retrieve a defensible universal numeric trigger for them. citeturn38search0turn35search0

Three source or population conflicts should be **preserved, not reconciled**. First, the pediatric **screening** flag `eGFR <90 mL/min/1.73 m2` for children/adolescents >2 years coexists with the chronic CKD/referral threshold `eGFR <60 mL/min/1.73 m2 for ≥3 months`; they are not interchangeable. Second, pediatric nephrotic-range spot proteinuria `>2 mg/mg` conflicts materially with the mixed-population/paywalled SI threshold `>350 mg/mmol`; this is not a rounding artifact and should remain dual-represented. Third, **albuminuria** (`uACR`) and **total proteinuria** (`UPCR`) are different analytes and should not be silently cross-walked, even when numerically adjacent categories appear similar. citeturn31view1turn32search1turn34search0 fileciteturn2file1

A smaller but still meaningful representation conflict exists in some KDIGO-adjacent renderings of `mg/mmol` albuminuria boundaries. In this output I kept the RF-KID-001 bundle representation `A1 <3`, `A2 3–30`, `A3 >30 mg/mmol`, but mirrored figures sometimes render the middle band as `3–29` and the severe band as `≥30`. That discrepancy should be preserved as a **source-formatting conflict**, not silently harmonized. fileciteturn2file0 citeturn33search7

## Limits

Some important numerics remain attached to **paywalled or rights-restricted** sources. The clearest example is the `mg/mmol` UPCR thresholds from Kaminska 2020. I retained them because they are already present in the RF-KID-001 bundle, but their source remains paywalled and I did not attempt to “recover” them from lower-quality derivative pages. fileciteturn2file0

A few rows necessarily rely on authoritative **secondary retrieval paths** rather than the original publisher-hosted table. That is most relevant for the AAP 2017 pediatric hypertension categories and for some KDIGO 2024 category displays, where open summaries or companion tools reproduce the official boundaries more cleanly than the original publisher interface exposed in this session. Those rows are still usable as candidate rows, but they should be high-priority items for the Research Foundry verifier to bind passage-by-passage against the source-of-record. citeturn27view1turn33search0turn31view1