"""ACT-403 (public-multiuser Phase 4): live-session ``multi_user`` regression.

Proves the DI-1 two-part gate (:meth:`FoundryConfig.deployment_mode_validate`
condition (d), FR-13) is wired end-to-end AND that a real ``multi_user``
session actually works once the gate passes — not just that the config-level
predicate returns the right booleans (that unit coverage already lives in
``tests/unit/test_deployment_mode.py`` and ``tests/test_deployment_mode_cli_and_app.py``).

This file adds three things neither of those covers:

1. ``create_app()`` fails closed on condition (d) SPECIFICALLY (ack=False,
   accepted-but-stale-status, and missing-artifact-file) with every other
   condition already satisfied — isolating (d) as the sole cause, at the
   real ``create_app()`` call site (not just the config-level predicate).
2. Once the gate passes, the composite auth chain (ACT-203) and the
   agent-job service-account identity binding (ACT-204, FR-12) actually work
   LIVE against the constructed app / same on-disk paths — a request
   authenticated by a service-account token resolves to the SA identity via
   ``GET /api/auth/identity``, and an agent job launched under that same
   ``multi_user`` config binds to the SA execution identity in the audit log.
3. ``single_user`` never needs DI-1 acceptance at all (byte-identical to
   pre-ACT-402 behaviour) — confirmed with NO audit artifact on disk and NO
   ack flag set.

NOTE: Bearer token values below are fixture-generated by
``token_service.issue_service_account_token`` (real random secrets, never a
literal secret-shaped string in source) — no PreToolUse secret-scan
workaround needed here (contrast ``tests/test_composite_auth_chain.py``,
which does need one for its hand-written provider-adapter fixture token).
"""

from __future__ import annotations

from pathlib import Path

import pytest
from fastapi import FastAPI
from fastapi.testclient import TestClient

from research_foundry.api.app import create_app
from research_foundry.config import FoundryConfig
from research_foundry.paths import FoundryPaths
from research_foundry.services import rbac_store, token_service
from research_foundry.services.agent_job_service import AgentJobService
from research_foundry.services.audit_service import list_events
from research_foundry.yamlio import dump_yaml, load_yaml

_MINIMAL_POLICY_SNAPSHOT = {"allowed_tools": ["search"], "data_scopes": []}
_DEFAULT_SA_ID = "svc_default_researcher"
_DEFAULT_SA_WORKSPACE = "default"


def _set_foundry_overrides(paths: FoundryPaths, overrides: dict) -> None:
    """Merge *overrides* into the ``foundry:`` block of ``foundry.yaml``."""
    foundry_yaml_path = paths.foundry_yaml
    existing: dict = load_yaml(foundry_yaml_path) or {}
    if "foundry" not in existing or not isinstance(existing.get("foundry"), dict):
        existing["foundry"] = {}
    for key, value in overrides.items():
        existing["foundry"][key] = value
    dump_yaml(existing, foundry_yaml_path)


def _write_audit(tmp_path: Path, *, status: str, name: str) -> Path:
    audit_path = tmp_path / name
    audit_path.write_text(f"---\nstatus: {status}\n---\n\nbody\n", encoding="utf-8")
    return audit_path


def _multi_user_config(
    tmp_foundry: FoundryPaths,
    tmp_path: Path,
    *,
    di1_ack: bool,
    audit_status: str | None,
    missing_audit: bool = False,
    bind_default_service_account: bool = True,
) -> FoundryConfig:
    """Build a ``multi_user`` config with (a)-(c) always satisfied, and (d)
    controlled independently by the three keyword args — so a caller can
    isolate condition (d) exactly as the phase-4 AC-3 suite requires.

    ``auth.provider=local_static`` with an EMPTY token list satisfies (a)
    without giving the provider adapter any credential of its own — the only
    way through auth in these tests is the composite-chain token-store path
    (ACT-203), which is the live behaviour this file is regression-testing.
    """
    auth_block: dict = {"provider": "local_static", "local_static": {"tokens": []}}
    if di1_ack:
        auth_block["di1_audit_acknowledged"] = True
    if missing_audit:
        auth_block["di1_audit_report_path"] = str(tmp_path / "does-not-exist.md")
    elif audit_status is not None:
        audit_path = _write_audit(tmp_path, status=audit_status, name="di1-audit.md")
        auth_block["di1_audit_report_path"] = str(audit_path)

    overrides: dict = {"deployment_mode": "multi_user", "auth": auth_block}
    if bind_default_service_account:
        overrides["agents"] = {"default_service_account_id": _DEFAULT_SA_ID}
    _set_foundry_overrides(tmp_foundry, overrides)
    return FoundryConfig(paths=tmp_foundry)


def _seed_default_service_account(cfg: FoundryConfig) -> token_service.IssuedToken:
    """Create the ``agents.default_service_account_id`` SA + issue it a token."""
    conn = rbac_store.bootstrap(cfg.paths)
    try:
        rbac_store.upsert_workspace(conn, _DEFAULT_SA_WORKSPACE, "Default")
        rbac_store.create_service_account(
            conn,
            service_account_id=_DEFAULT_SA_ID,
            name="Default Researcher Service Account",
            workspace_id=_DEFAULT_SA_WORKSPACE,
            role="researcher",
            created_by="test-harness",
        )
    finally:
        conn.close()
    return token_service.issue_service_account_token(
        cfg.paths, service_account_id=_DEFAULT_SA_ID
    )


# ---------------------------------------------------------------------------
# create_app() fails closed on condition (d) in isolation — the other three
# conditions are already satisfied by _multi_user_config's defaults.
# ---------------------------------------------------------------------------


class TestCreateAppGateConditionDInIsolation:
    def test_both_halves_satisfied_app_starts(self, tmp_foundry, tmp_path):
        config = _multi_user_config(
            tmp_foundry, tmp_path, di1_ack=True, audit_status="accepted"
        )
        app_instance = create_app(config)

        assert isinstance(app_instance, FastAPI)
        # (b)/(c) come from the multi_user preset defaults — confirm they
        # actually resolved to enforced, not just that create_app() didn't
        # raise for an unrelated reason.
        assert app_instance.state.rbac_enforced is True
        assert app_instance.state.workspace_isolation_enforced is True

    def test_ack_false_fails_closed(self, tmp_foundry, tmp_path):
        config = _multi_user_config(
            tmp_foundry, tmp_path, di1_ack=False, audit_status="accepted"
        )
        with pytest.raises(ValueError) as excinfo:
            create_app(config)
        message = str(excinfo.value)
        assert "(d)" in message
        assert "di1_audit_acknowledged" in message
        assert "(a)" not in message
        assert "(b)" not in message
        assert "(c)" not in message

    def test_ack_true_but_audit_status_not_accepted_fails_closed(self, tmp_foundry, tmp_path):
        """The ack flag alone must never satisfy (d) — a stale doc with the
        flag flipped is still an unmet two-part gate (this is the exact
        failure mode the WKSP-304 AAR flagged: a self-certified "done" that
        the artifact itself doesn't actually confirm)."""
        config = _multi_user_config(
            tmp_foundry, tmp_path, di1_ack=True, audit_status="pending-human-signoff"
        )
        with pytest.raises(ValueError) as excinfo:
            create_app(config)
        message = str(excinfo.value)
        assert "(d)" in message
        assert "pending-human-signoff" in message

    def test_missing_audit_file_fails_closed_same_as_not_accepted(self, tmp_foundry, tmp_path):
        config = _multi_user_config(
            tmp_foundry, tmp_path, di1_ack=True, audit_status=None, missing_audit=True
        )
        with pytest.raises(ValueError) as excinfo:
            create_app(config)
        message = str(excinfo.value)
        assert "(d)" in message
        assert "not found" in message

    def test_both_halves_missing_fails_closed_naming_only_d(self, tmp_foundry, tmp_path):
        """Neither ack nor an accepted artifact configured at all (the
        out-of-the-box multi_user state before an operator has done
        anything) — still isolated to (d) alone, since (a)-(c) are
        satisfied by this helper's other defaults."""
        config = _multi_user_config(
            tmp_foundry, tmp_path, di1_ack=False, audit_status=None
        )
        with pytest.raises(ValueError) as excinfo:
            create_app(config)
        message = str(excinfo.value)
        assert "(a)" not in message
        assert "(b)" not in message
        assert "(c)" not in message
        assert "(d)" in message
        assert "1 unmet condition" in message


# ---------------------------------------------------------------------------
# single_user never needs DI-1 acceptance — confirmed with NOTHING configured
# (no ack flag, no audit artifact anywhere) alongside an otherwise-unsafe
# auth.provider — a total no-op exactly as FR-2 requires.
# ---------------------------------------------------------------------------


class TestSingleUserNeverRequiresDi1Acceptance:
    def test_single_user_starts_with_no_di1_state_at_all(self, tmp_foundry):
        _set_foundry_overrides(
            tmp_foundry,
            {"deployment_mode": "single_user", "auth": {"provider": "none"}},
        )
        config = FoundryConfig(paths=tmp_foundry)

        app_instance = create_app(config)  # must not raise

        assert isinstance(app_instance, FastAPI)

    def test_single_user_di1_audit_acknowledged_accessor_default_false(self, tmp_foundry):
        """Sanity check on the underlying accessor too — single_user's
        no-op is because the gate never evaluates (d) for this mode, not
        because the flag happens to default True."""
        config = FoundryConfig(paths=tmp_foundry)
        assert config.di1_audit_acknowledged() is False


# ---------------------------------------------------------------------------
# Live session: once the gate passes, the composite auth chain (ACT-203)
# resolves a service-account Bearer token to the SA identity for real, over
# the actual ASGI stack (not a unit-level mock of the middleware).
# ---------------------------------------------------------------------------


@pytest.fixture()
def gate_passed_app(tmp_foundry, tmp_path):
    """A fully gate-passing ``multi_user`` app + its backing config."""
    config = _multi_user_config(tmp_foundry, tmp_path, di1_ack=True, audit_status="accepted")
    app_instance = create_app(config)
    client = TestClient(app_instance, raise_server_exceptions=True)
    return client, config


class TestLiveSessionCompositeAuthChain:
    def test_service_account_token_resolves_to_sa_identity(self, gate_passed_app):
        client, config = gate_passed_app
        issued = _seed_default_service_account(config)

        resp = client.get(
            "/api/auth/identity",
            headers={"Authorization": f"Bearer {issued.plaintext}"},
        )

        assert resp.status_code == 200
        body = resp.json()
        assert body["user_id"] == _DEFAULT_SA_ID
        assert body["workspace_id"] == _DEFAULT_SA_WORKSPACE
        assert "researcher" in body["roles"]

    def test_no_credential_still_401_under_passed_gate(self, gate_passed_app):
        """The gate passing is orthogonal to per-request auth — a live
        multi_user session still rejects unauthenticated callers."""
        client, _config = gate_passed_app
        resp = client.get("/api/auth/identity")
        assert resp.status_code == 401

    def test_revoked_service_account_token_401_under_passed_gate(self, gate_passed_app):
        client, config = gate_passed_app
        issued = _seed_default_service_account(config)
        token_service.revoke_token(config.paths, issued.token_id)

        resp = client.get(
            "/api/auth/identity",
            headers={"Authorization": f"Bearer {issued.plaintext}"},
        )

        assert resp.status_code == 401

    def test_health_exempt_under_passed_multi_user_gate(self, gate_passed_app):
        client, _config = gate_passed_app
        resp = client.get("/health")
        assert resp.status_code == 200


# ---------------------------------------------------------------------------
# Live session: agent-job service-account identity binding (ACT-204, FR-12)
# actually activates under this same gate-passed multi_user config/paths.
# ---------------------------------------------------------------------------


class TestLiveSessionAgentJobServiceAccountBinding:
    def test_agent_job_binds_to_sa_execution_identity_and_audit_records_both(
        self, gate_passed_app
    ):
        client, config = gate_passed_app
        _seed_default_service_account(config)

        # Launch the job against the EXACT same on-disk paths the live app
        # is serving from — proving the binding is real for this session,
        # not merely a config-level unit assertion in isolation.
        service = AgentJobService(config.paths)
        job = service.create_job(
            provider="claude_agent_sdk",
            model_profile="rf_synthesize_deep",
            request_kind="research",
            policy_snapshot=dict(_MINIMAL_POLICY_SNAPSHOT),
            project_id="test-project",
            workspace_id=_DEFAULT_SA_WORKSPACE,
            created_by="human_caller_alice",
        )

        assert job.created_by == _DEFAULT_SA_ID

        events = list_events(config.paths, mutation_type="agent_job_launched")
        matching = [e for e in events["items"] if e["target_ref"] == job.agent_job_id]
        assert len(matching) == 1
        event = matching[0]
        assert event["actor_user_id"] == _DEFAULT_SA_ID
        assert event["actor_workspace_id"] == _DEFAULT_SA_WORKSPACE
        snapshot = event["policy_snapshot"]
        assert snapshot["triggering_identity"] == "human_caller_alice"
        assert snapshot["executing_identity"] == _DEFAULT_SA_ID
        assert snapshot["deployment_mode"] == "multi_user"

        # And the SA's own token still resolves live through the same app —
        # tying the "who executed this" audit identity back to a credential
        # that a real caller could authenticate as in this session.
        issued = token_service.issue_service_account_token(
            config.paths, service_account_id=_DEFAULT_SA_ID
        )
        resp = client.get(
            "/api/auth/identity",
            headers={"Authorization": f"Bearer {issued.plaintext}"},
        )
        assert resp.status_code == 200
        assert resp.json()["user_id"] == event["actor_user_id"]

    def test_without_default_service_account_configured_binding_stays_off(
        self, tmp_foundry, tmp_path
    ):
        """Regression companion (AC-5): even with the DI-1 gate passed and
        multi_user active, the SA binding is a SEPARATE opt-in
        (``agents.default_service_account_id``) — omitting it leaves
        agent-job identity binding untouched, gate or no gate."""
        config = _multi_user_config(
            tmp_foundry,
            tmp_path,
            di1_ack=True,
            audit_status="accepted",
            bind_default_service_account=False,
        )
        create_app(config)  # gate still passes independently of this knob

        service = AgentJobService(config.paths)
        job = service.create_job(
            provider="claude_agent_sdk",
            model_profile="rf_synthesize_deep",
            request_kind="research",
            policy_snapshot=dict(_MINIMAL_POLICY_SNAPSHOT),
            project_id="test-project",
            workspace_id=_DEFAULT_SA_WORKSPACE,
            created_by="human_caller_alice",
        )

        assert job.created_by == "human_caller_alice"
        events = list_events(config.paths, mutation_type="agent_job_launched")
        assert events["items"] == []
