# Pediatric Growth Candidate Patterns

## Scope note

The rows below are net-new candidate patterns aligned to the requested angles. I did not restate the already-held areas you said are already covered: faltering-growth indicator-base conflict, chart-dependent threshold binding, and the preterm/VLBW corrected-age branch.

## Extraction table

| Pattern ID | Condition / pattern | Trigger | Threshold + UCUM unit | Population / age band | Chart or standard anchor | Source | Access status | Direction / effect | Conflicts-with / caveat |
|---|---|---|---|---|---|---|---|---|---|
| GS-SS-01 | Mid-parental target height formula | Biologic parental heights available during short-stature work-up | Boys: `([father height]+[mother height]+13 cm)/2` `cm` | Boys; projected adult target height | Tanner mid-parental-height method | SRC-AAFP-2015 — `https://www.aafp.org/afp/2015/0701/p43` (2015) citeturn23view0turn23view2 | open-access | note | Formula estimates target adult height; not itself a centile threshold. |
| GS-SS-02 | Mid-parental target height formula | Biologic parental heights available during short-stature work-up | Girls: `([father height]-13 cm+[mother height])/2` `cm` | Girls; projected adult target height | Tanner mid-parental-height method | SRC-AAFP-2015 — `https://www.aafp.org/afp/2015/0701/p43` (2015) citeturn23view0turn23view2 | open-access | note | Formula estimates target adult height; not itself a centile threshold. |
| GS-SS-03 | Family target-height band | Mid-parental height already calculated | `±8.5 cm` around mid-parental height `cm` | Boys and girls; anticipated adult height | Target-height band around mid-parental height | SRC-CM-GF-2026 — `https://www.childrensmercy.org/health-care-providers/pediatrician-guides/endocrinology/growth-failure/` (2026 site version; publication date not stated) citeturn20view0 | open-access | note | Institutional pediatric-endocrinology page; not a national guideline. |
| GS-SS-04 | Height below family-expected centile range | Child’s length/height centile compared with mid-parental centile | `>2 centile spaces` below mid-parental centile `centile-space` | Infants and children with parental heights available | UK-WHO growth charts / mid-parental centile | SRC-NICE-NG75 — `https://www.nice.org.uk/guidance/ng75/chapter/Recommendations` (2017) citeturn5search0 | open-access | referral-readiness | UK centile-space wording is chart-specific; do not transpose directly to CDC centile spacing. |
| GS-SS-05 | Projected adult height discordant with family target | Projected adult height compared with mid-parental height | `>10 cm` difference from mid-parental height `cm` | Children under height evaluation | Projected adult height versus mid-parental height | SRC-AAFP-2015 — `https://www.aafp.org/afp/2015/0701/p43` (2015) citeturn23view2 | open-access | referral-readiness | Source states “more than 10 cm” and also “more than 2 standard deviations.” |
| GS-SS-06 | Short-stature screen | Single attained height/length value | `<3rd percentile` or `<−2 SD` | Children and adolescents | Age- and sex-appropriate stature-for-age chart | SRC-AAFP-2015 — `https://www.aafp.org/afp/2015/0701/p43` (2015) citeturn23view3 | open-access | note | Chart family still must match age and measurement method. |
| GS-SS-07 | Severe short stature | Single attained height value | `<−3 SD` | Age ≥2 years in referral algorithm | WHO/CDC stature-for-age as used in endocrine referral workflow | SRC-CM-GF-2026 — `https://www.childrensmercy.org/health-care-providers/pediatrician-guides/endocrinology/growth-failure/` (2026 site version; publication date not stated) citeturn20view0 | open-access | referral-readiness | Institutional algorithm. |
| GS-SS-08 | Impaired height velocity | Serial height measurements over time | `<5.5 cm/a` | Age 2–4 years | Serial stature velocity | SRC-CM-GF-2026 — `https://www.childrensmercy.org/health-care-providers/pediatrician-guides/endocrinology/growth-failure/` (2026 site version; publication date not stated) citeturn20view0 | open-access | referral-readiness | Institutional algorithm; measurements should be at least 6 months apart. |
| GS-SS-09 | Impaired height velocity | Serial height measurements over time | `<5.0 cm/a` | Age 4–6 years | Serial stature velocity | SRC-CM-GF-2026 — `https://www.childrensmercy.org/health-care-providers/pediatrician-guides/endocrinology/growth-failure/` (2026 site version; publication date not stated) citeturn20view0 | open-access | referral-readiness | Institutional algorithm; measurements should be at least 6 months apart. |
| GS-SS-10 | Impaired height velocity | Serial height measurements over time | `<4.0 cm/a` | Boys, age 6 years to puberty | Serial stature velocity | SRC-CM-GF-2026 — `https://www.childrensmercy.org/health-care-providers/pediatrician-guides/endocrinology/growth-failure/` (2026 site version; publication date not stated) citeturn20view0 | open-access | referral-readiness | Institutional algorithm; measurements should be at least 6 months apart. |
| GS-SS-11 | Impaired height velocity | Serial height measurements over time | `<4.5 cm/a` | Girls, age 6 years to puberty | Serial stature velocity | SRC-CM-GF-2026 — `https://www.childrensmercy.org/health-care-providers/pediatrician-guides/endocrinology/growth-failure/` (2026 site version; publication date not stated) citeturn20view0 | open-access | referral-readiness | Institutional algorithm; measurements should be at least 6 months apart. |
| GS-BMI-01 | WHO under-5 BMI-for-age adiposity-risk flag | BMI-for-age above WHO median | `>+1 SD` | Age 0–5 years | WHO Child Growth Standards BMI-for-age | SRC-WHO-QA-2025 — `https://www.who.int/news-room/questions-and-answers/item/child-growth-standards` (2025) citeturn25view3 | open-access | note / flag | WHO under-5 uses z-score descriptors; not interchangeable with CDC BMI percentiles. |
| GS-BMI-02 | WHO under-5 overweight | BMI-for-age above WHO median | `>+2 SD` | Age 0–5 years | WHO Child Growth Standards BMI-for-age | SRC-WHO-QA-2025 — `https://www.who.int/news-room/questions-and-answers/item/child-growth-standards` (2025) citeturn25view3 | open-access | flag | WHO under-5 cut-offs are z-score based. |
| GS-BMI-03 | WHO under-5 obesity | BMI-for-age above WHO median | `>+3 SD` | Age 0–5 years | WHO Child Growth Standards BMI-for-age | SRC-WHO-QA-2025 — `https://www.who.int/news-room/questions-and-answers/item/child-growth-standards` (2025) citeturn25view3 | open-access | flag | WHO under-5 cut-offs are z-score based. |
| GS-BMI-04 | CDC overweight | BMI percentile category | `≥85th` to `<95th percentile` `percentile` | Age 2–20 years | 2000 CDC BMI-for-age | SRC-CDC-BMI-2025 — `https://www.cdc.gov/growth-chart-training/hcp/using-bmi/summary.html` (2025) citeturn21view1turn21view2 | public-domain | flag | CDC percentiles are chart-family specific. |
| GS-BMI-05 | CDC obesity | BMI percentile category | `≥95th percentile` `percentile` | Age 2–20 years | 2000 CDC BMI-for-age | SRC-CDC-BMI-2025 — `https://www.cdc.gov/growth-chart-training/hcp/using-bmi/summary.html` (2025) citeturn21view1turn21view3 | public-domain | flag | CDC percentiles are chart-family specific. |
| GS-BMI-06 | CDC severe obesity | Very high BMI on growth chart | `≥120% of 95th percentile` or `≥35 kg/m2` | Age 2–20 years | CDC BMI-for-age / CDC extended BMI-for-age | SRC-CDC-BMI-2025 — `https://www.cdc.gov/growth-chart-training/hcp/using-bmi/summary.html` (2025) citeturn21view1turn21view3 | public-domain | referral-readiness | Severe obesity is a subset of obesity in the CDC source. |
| GS-BMI-07 | CDC extended BMI chart selection rule | Plotting or monitoring very high BMI | Use extended chart if `>97th percentile`; either chart acceptable for `95th–97th percentile` `percentile` | Age 2–20 years | CDC Extended BMI-for-age Growth Charts | SRC-CDC-BMI-2025 — `https://www.cdc.gov/growth-chart-training/hcp/using-bmi/summary.html` (2025) citeturn21view1 | public-domain | note | This is a chart-selection rule, not a diagnostic category. |
| GS-HC-01 | Microcephaly branch | OFC below expected for age/sex | `<−2 SD` | Pediatric OFC assessment | Age/sex-specific OFC chart; WHO HC charts available through age 5 years | SRC-AAN-MIC-2009 — `https://pmc.ncbi.nlm.nih.gov/articles/PMC2744281/` (2009) citeturn9search1 | open-access | flag | Open secondary source states WHO HC charts are available through age 5; do not assume interchangeability with older-child Nellhaus plotting. |
| GS-HC-02 | Severe microcephaly branch | More extreme OFC deficit | `<−3 SD` | Pediatric OFC assessment | Age/sex-specific OFC chart | SRC-AAN-MIC-2009 — `https://pmc.ncbi.nlm.nih.gov/articles/PMC2744281/` (2009) citeturn9search1 | open-access | referral-readiness | Source describes `<−3 SD` as severe microcephaly. |
| GS-HC-03 | Macrocephaly branch | OFC above expected for age/sex | `>+2 SD` | Pediatric OFC assessment | Age/sex-specific OFC chart | SRC-PMC-MAC-2022 — `https://pmc.ncbi.nlm.nih.gov/articles/PMC8795981/` (2022) citeturn8search2 | open-access | flag | Review definition is chart-agnostic; chart family still matters operationally. |
| GS-HC-04 | Clinically relevant macrocephaly | OFC substantially above expected for age/sex | `>+3 SD` | Pediatric OFC assessment | Age/sex-specific OFC chart | SRC-PMC-MAC-2022 — `https://pmc.ncbi.nlm.nih.gov/articles/PMC8795981/` (2022) citeturn8search2 | open-access | referral-readiness | Source notes that some children between +2 and +3 SD are healthy; >+3 SD is described as clinically relevant. |
| GS-HC-05 | Older-child HC chart branch | Child exceeds WHO/CDC infant HC chart age range | `>36 mo` | Children older than 36 months | Nellhaus charts for older-child head circumference evaluation | SRC-AAN-MIC-2009 — `https://pmc.ncbi.nlm.nih.gov/articles/PMC2744281/` (2009) citeturn9search1 | open-access | scope-exit / chart-selection prompt | This is a chart-selection threshold, not a pathology threshold. Original Nellhaus chart article is rights-restricted. |
| GS-HC-06 | Nellhaus-based macrocephaly criterion | Suspected benign external hydrocephalus workflow | `>97.5th percentile` `percentile` | Children evaluated in a pediatric neurosurgical unit BEH pathway | Nellhaus graphs | SRC-PMC-BEH-2025 — `https://pmc.ncbi.nlm.nih.gov/articles/PMC12072479/` (2025) citeturn9search0 | open-access | referral-readiness | Study-specific criterion; not a general pediatric consensus threshold. |
| GS-TR-01 | WHO→CDC chart transition rule | Child reaches chart-family transition point | `24 mo` | U.S. growth monitoring from infancy into childhood | WHO charts for `<24 mo`; CDC charts for `24–59 mo` | SRC-CDC-MMWR-2010 — `https://www.cdc.gov/mmwr/preview/mmwrhtml/rr5909a1.htm` (2010) citeturn26view0 | public-domain | note / chart-selection prompt | Threshold meaning changes across the transition because chart family changes. |
| GS-TR-02 | WHO under-24 screening cut-offs | Using WHO charts before transition | `2.3rd` and `97.7th percentile` or `±2 SD` | Children `<24 mo` | WHO curves in U.S. clinical use | SRC-CDC-MMWR-2010 — `https://www.cdc.gov/mmwr/preview/mmwrhtml/rr5909a1.htm` (2010) citeturn26view0turn26view2 | public-domain | note | Do not carry CDC 5th/95th semantics onto WHO curves. |
| GS-TR-03 | CDC post-transition screening semantics | Using CDC charts after transition | `5th` and `95th percentile` `percentile` | Children `24–59 mo` and older on CDC charts | CDC curves | SRC-CDC-MMWR-2010 — `https://www.cdc.gov/mmwr/preview/mmwrhtml/rr5909a1.htm` (2010) citeturn26view3turn26view0 | public-domain | note | Same MMWR warns that applying 5th/95th to WHO curves would overestimate abnormality. |
| GS-CUG-01 | Pediatric malnutrition mild velocity deficit | Two or more data points show reduced weight-gain velocity | `<75% of norm` | Age 1 month to `<2 y` | AND/ASPEN pediatric malnutrition indicators | SRC-ASPEN-2015 — DOI `10.1177/0884533614557642` (2015) citeturn14search0 | open-access | flag | Relative-to-norm threshold; the source does not convert this row to a single absolute `g/kg/d` value across all ages. |
| GS-CUG-02 | Pediatric malnutrition moderate velocity deficit | Two or more data points show reduced weight-gain velocity | `<50% of norm` | Age 1 month to `<2 y` | AND/ASPEN pediatric malnutrition indicators | SRC-ASPEN-2015 — DOI `10.1177/0884533614557642` (2015) citeturn14search0 | open-access | flag | Relative-to-norm threshold; age-specific expected gain still must be sourced from the referenced norm tables. |
| GS-CUG-03 | Pediatric malnutrition severe velocity deficit | Two or more data points show reduced weight-gain velocity | `<25% of norm` | Age 1 month to `<2 y` | AND/ASPEN pediatric malnutrition indicators | SRC-ASPEN-2015 — DOI `10.1177/0884533614557642` (2015) citeturn14search0 | open-access | referral-readiness | Relative-to-norm threshold; age-specific expected gain still must be sourced from the referenced norm tables. |
| GS-CUG-04 | Catch-up velocity target | Recovery from WFA z-score `−1` to `0` in `20 d` | `4.1 g/kg/d` | Male children, length `65–80 cm` | Golden-adjusted catch-up table | SRC-KARGER-FG-2024 — DOI `10.1159/000540930` (2024 online; journal issue 2025) citeturn28view0turn27view0 | unknown | note | Specific to the `65–80 cm` length band and a `20 d` catch-up horizon. |
| GS-CUG-05 | Catch-up velocity target | Recovery from WFA z-score `−1` to `0` in `20 d` | `4.4 g/kg/d` | Female children, length `65–80 cm` | Golden-adjusted catch-up table | SRC-KARGER-FG-2024 — DOI `10.1159/000540930` (2024 online; journal issue 2025) citeturn28view0turn27view0 | unknown | note | Specific to the `65–80 cm` length band and a `20 d` catch-up horizon. |
| GS-CUG-06 | Catch-up velocity target | Recovery from WFA z-score `−2` to `0` in `20 d` | `8.0 g/kg/d` | Male children, length `65–80 cm` | Golden-adjusted catch-up table | SRC-KARGER-FG-2024 — DOI `10.1159/000540930` (2024 online; journal issue 2025) citeturn28view0turn27view0 | unknown | note | Specific to the `65–80 cm` length band and a `20 d` catch-up horizon. |
| GS-CUG-07 | Catch-up velocity target | Recovery from WFA z-score `−2` to `0` in `20 d` | `8.7 g/kg/d` | Female children, length `65–80 cm` | Golden-adjusted catch-up table | SRC-KARGER-FG-2024 — DOI `10.1159/000540930` (2024 online; journal issue 2025) citeturn28view0turn27view0 | unknown | note | Specific to the `65–80 cm` length band and a `20 d` catch-up horizon. |

## Sources

| Source ID | Full citation | DOI / stable URL | Year | License / access |
|---|---|---|---|---|
| SRC-NICE-NG75 | National Institute for Health and Care Excellence. *Faltering growth: recognition and management of faltering growth in children. NG75, Recommendations.* | `https://www.nice.org.uk/guidance/ng75/chapter/Recommendations` | 2017 | license not stated / open-access citeturn5search0 |
| SRC-AAFP-2015 | Lipman TH, Hench KD, Benyi T, Delaune J, Gilluly KA, Johnson L, et al. *Evaluation of Short and Tall Stature in Children.* *American Family Physician.* | `https://www.aafp.org/afp/2015/0701/p43` | 2015 | license not stated / open-access citeturn22view5turn23view0 |
| SRC-CM-GF-2026 | Children’s Mercy Kansas City. *Evaluating Growth Failure.* Pediatric guide for health care providers. | `https://www.childrensmercy.org/health-care-providers/pediatrician-guides/endocrinology/growth-failure/` | 2026 site version; publication date not stated | license not stated / open-access citeturn20view0 |
| SRC-CDC-BMI-2025 | Centers for Disease Control and Prevention. *Summary and References: Using BMI-for-Age Growth Charts.* Growth Chart Training. | `https://www.cdc.gov/growth-chart-training/hcp/using-bmi/summary.html` | 2025 | U.S. government public domain / public-domain citeturn21view1 |
| SRC-CDC-MMWR-2010 | Grummer-Strawn LM, Reinold C, Krebs NF. *Use of World Health Organization and CDC Growth Charts for Children Aged 0–59 Months in the United States.* *MMWR Recommendations and Reports.* | `https://www.cdc.gov/mmwr/preview/mmwrhtml/rr5909a1.htm` | 2010 | U.S. government public domain / public-domain citeturn22view4turn26view0 |
| SRC-WHO-QA-2025 | World Health Organization. *Child growth standards.* Q&A. | `https://www.who.int/news-room/questions-and-answers/item/child-growth-standards` | 2025 | license not stated / open-access citeturn24view0turn25view3 |
| SRC-WHO-MAL-2026 | World Health Organization. *Malnutrition in children.* Nutrition Landscape Information System information page. | `https://www.who.int/data/nutrition/nlis/info/malnutrition-in-children` | year not stated on page; current WHO page snapshot 2026 | license not stated / open-access citeturn24view4turn25view1 |
| SRC-WHO-HC-2026 | World Health Organization. *Head circumference for age.* WHO Child Growth Standards tools page. | `https://www.who.int/tools/child-growth-standards/standards/head-circumference-for-age` | year not stated on page; current WHO page snapshot 2026 | license not stated / open-access citeturn24view2turn25view0 |
| SRC-AAN-MIC-2009 | Ashwal S, Michelson D, Plawner L, Dobyns WB. *Practice Parameter: Evaluation of the Child With Microcephaly.* *Neurology.* PMCID: PMC2744281. | `https://pmc.ncbi.nlm.nih.gov/articles/PMC2744281/` | 2009 | open-access via PMC citeturn9search1 |
| SRC-PMC-MAC-2022 | Sampson MA, et al. *Diagnostic Approach to Macrocephaly in Children.* PMCID: PMC8795981. | `https://pmc.ncbi.nlm.nih.gov/articles/PMC8795981/` | 2022 | open-access via PMC citeturn8search2 |
| SRC-PMC-BEH-2025 | Eide PK, et al. *Continuous Intracranial Pressure Monitoring in Children with ‘Benign’ External Hydrocephalus.* PMCID: PMC12072479. | `https://pmc.ncbi.nlm.nih.gov/articles/PMC12072479/` | 2025 | open-access via PMC citeturn9search0 |
| SRC-KARGER-FG-2024 | Meyer R. *An Update on the Diagnosis and Management of Faltering Growth and Catch-Up Growth in Young Children.* *Annals of Nutrition and Metabolism.* | DOI `10.1159/000540930` | 2024 online; issue dated 2025 | license not stated / access unknown citeturn27view0turn28view0 |
| SRC-WILEY-CUG-2023 | Cooke R, Goulet O, Huysentruyt K, Joosten K, Khadilkar AV, Mao M, et al. *Catch-Up Growth in Infants and Young Children With Faltering Growth.* *Journal of Pediatric Gastroenterology and Nutrition.* | DOI `10.1097/MPG.0000000000003784` | 2023 | open-access citeturn12search0turn12search1 |
| SRC-ASPEN-2015 | Becker P, Carney LN, Corkins MR, et al. *Consensus Statement of the Academy of Nutrition and Dietetics/American Society for Parenteral and Enteral Nutrition: Indicators Recommended for the Identification and Documentation of Pediatric Malnutrition.* *Nutrition in Clinical Practice.* | DOI `10.1177/0884533614557642` | 2015 | free access / open-access citeturn14search0 |
| SRC-NELLHAUS-1968 | Nellhaus G. *Head Circumference from Birth to Eighteen Years: Practical Composite International and Interracial Graphs.* *Pediatrics.* | DOI `10.1542/peds.41.1.106` | 1968 | paywalled citeturn7search2 |

## Gaps

I did not find an independently retrievable public-domain or open-access **numeric downward-height-percentile-line trigger** for short-stature work-up that matched the way NICE gives a parent-centile-distance trigger; the open sources I found were either narrative or institutional rather than a single public guideline table. citeturn5search0turn20view0turn23view2

I did not find an official CDC or WHO **numeric BMI-percentile trajectory-crossing cut-off** analogous to the category thresholds above; the public guideline sources were strong on category boundaries and chart-selection thresholds, but not on a canonical percentile-crossing rule. citeturn21view1turn24view0

For **Nellhaus raw chart-table thresholds**, the original 1968 *Pediatrics* article is rights-restricted/paywalled, so I did not extract raw chart values from the original source. I used open secondary sources for older-child chart selection and one study-specific Nellhaus percentile criterion instead. citeturn7search2turn9search1turn9search0

I did not re-extract **INTERGROWTH-21st preterm corrected-age thresholds** because your prompt explicitly marked the preterm/VLBW corrected-age branch as already held and out of scope for re-derivation.