# RF-CBC-002 Pediatric CBC Deepen Pass

## Summary

This deepen pass produced **27 net-new candidate rows** and avoided re-emitting the four already-committed patterns. The strongest **openly retrievable numeric anchors** came from CALIPER 2020 for age-banded WBC, ALC, AMC, and MCV intervals; open pediatric ITP guidance for platelet action bands; open ASH pediatric leukocytosis guidance for leukemoid and hyperleukocytosis thresholds; open pediatric eosinophilia cohorts; and open severe aplastic anemia criteria. fileciteturn0file0 fileciteturn0file1 fileciteturn0file2 citeturn7search0turn21search1turn25search0turn22search4turn24search3turn16search0

Where a row is derived from a **reference interval boundary** rather than a source-stated disease cutoff, I labeled it **`inference`** instead of `assertion`. That distinction matters most for the CALIPER-based leukocytosis, lymphocytosis, monocytosis, and MCV rows: they are useful **fallback candidate bands**, but they should not outrank the module’s already-committed **local-lab-range precedence** behavior. fileciteturn0file0 citeturn7search0turn2search1

## Scope and retrieval strategy

The supplied materials frame this as a **deepen pass on RF-CBC-002** for the pediatric CBC suite, with the existing bundle already containing 20 sources and four committed patterns that must not be re-surfaced. I treated the table below as a **candidate-only synthesis**, not verified clinical evidence, and prioritized rows where the **exact threshold was independently retrievable**, preferably from open or openly indexed sources. fileciteturn0file0 fileciteturn0file1 fileciteturn0file2

Because the existing bundle’s **CALIPER 2023 Mindray** paper is bibliographic in the evidence file but its numeric tables are paywalled, I grounded most interval-bearing rows to the **publicly retrievable CALIPER 2020 DxH 900** tables/snippets instead. That gave exact pediatric WBC, ALC, AMC, eosinophil, neutrophil, and MCV numbers in a retrievable form, while still staying within the CALIPER program the module requested. fileciteturn0file2 citeturn0search0turn2search1turn4search0turn7search0

## Net-new candidate-pattern table

| # | candidate_id | condition | trigger | threshold | age_band | direction | source_citation | access_status | retrievable_numeric | classification | notes |
|---|---|---|---|---|---|---|---|---|---|---|---|
| 1 | itp-diagnostic-thrombocytopenia | primary ITP candidate | isolated thrombocytopenia without other cytopenias or systemic illness | `<100 10*9/L` | all | below | Braga 2013; DOI `10.5581/1516-8484.20130105` citeturn21search1 | open-access | yes | assertion | Diagnosis remains exclusionary; platelet threshold alone is insufficient. |
| 2 | itp-treatment-threshold | ITP treatment-consideration band | newly diagnosed child with ITP and grades 0–2 bleeding or limited quality-of-life impact | `<20 10*9/L` | all | below | Ye 2022; DOI `10.1002/ped4.12305` citeturn25search0 | open-access | yes | assertion | Guideline explicitly keeps bleeding severity primary and platelet count secondary. |
| 3 | itp-mucosal-bleeding-band | higher mucosal-bleeding likelihood band in pediatric ITP | child or adolescent with ITP, especially epistaxis or other mucosal bleeding | `<10 10*9/L` | all | below | Braga 2013; DOI `10.5581/1516-8484.20130105` citeturn12search6turn21search1 | open-access | yes | assertion | Open guideline summarizes underlying pediatric evidence; useful as an action band, not as a diagnosis. |
| 4 | itp-emergency-bleeding-band | highest serious-bleeding band in pediatric ITP | child or adolescent with ITP | `<5 10*9/L` | all | below | Braga 2013; DOI `10.5581/1516-8484.20130105` citeturn12search6turn21search1 | open-access | yes | assertion | Guideline summary reports clinically significant bleeding much more often at this level. |
| 5 | dic-consumptive-platelet-component | consumptive coagulopathy candidate | thrombocytopenia with suspected DIC physiology | `<80 10*9/L or >50 % fall in 24 h` | all | below | Kunwar 2021; DOI `10.7759/cureus.17682` citeturn13search3turn20search0 | open-access | yes | assertion | Platelet component of a pediatric DIC score; requires coagulation-marker context and should not stand alone. |
| 6 | ttp-adamts13-severe-deficiency | TTP-pattern differentiator | thrombocytopenia with microangiopathic hemolysis or schistocytes and organ injury | `<10 %` | all | below | Joly 2018; DOI `10.1111/ejh.13107` citeturn13search1 | open-access | yes | assertion | Not CBC-only, but a high-value differential threshold for the consumptive or TMA branch. |
| 7 | saa-platelet-criterion | aplastic-anemia pancytopenia criterion | suspected aplastic anemia with multilineage cytopenia | `<20 10*9/L` | all | below | Babushok 2024; DOI `10.1182/bloodadvances.2023011642` citeturn16search0 | open-access | yes | assertion | Modified Camitta criterion; pattern is referral or work-up, not final diagnosis. |
| 8 | saa-reticulocyte-criterion | aplastic-anemia pancytopenia criterion | suspected aplastic anemia with multilineage cytopenia | `<60 10*9/L` | all | below | Babushok 2024; DOI `10.1182/bloodadvances.2023011642` citeturn16search0 | open-access | yes | assertion | Use with marrow cellularity and another cytopenia criterion. |
| 9 | vsaa-anc-criterion | very-severe aplastic-anemia referral band | suspected aplastic anemia with multilineage cytopenia | `<0.2 10*9/L` | all | below | Babushok 2024; DOI `10.1182/bloodadvances.2023011642` citeturn16search0 | open-access | yes | assertion | Distinct aplastic-anemia context; not the already-committed congenital-neutropenia marrow rule. |
| 10 | wbc-leukocytosis-infancy | age-banded leukocytosis | WBC above CALIPER upper reference limit | `>13.2 10*9/L` | 0-<3 y | above | Tahmasebi 2020; DOI `10.1093/ajcp/aqaa059` citeturn2search1 | open-access | yes | inference | Inferred from the CALIPER upper RI; analyzer-specific fallback candidate only. |
| 11 | wbc-leukocytosis-preschool | age-banded leukocytosis | WBC above CALIPER upper reference limit | `>11.5 10*9/L` | 3-<5 y | above | Tahmasebi 2020; DOI `10.1093/ajcp/aqaa059` citeturn2search1 | open-access | yes | inference | Inferred from the CALIPER upper RI; analyzer-specific fallback candidate only. |
| 12 | wbc-leukocytosis-school-age-plus | age-banded leukocytosis | WBC above CALIPER upper reference limit | `>10.2 10*9/L` | 5-<21 y | above | Tahmasebi 2020; DOI `10.1093/ajcp/aqaa059` citeturn2search1 | open-access | yes | inference | Inferred from the CALIPER upper RI; analyzer-specific fallback candidate only. |
| 13 | leukemoid-reaction-band | leukemoid reaction candidate | marked leukocytosis, typically neutrophilic with immature myeloid forms or left shift | `>50 10*9/L` | all | above | Satty 2023; DOI `10.1182/hematology.2023000464` citeturn11search3turn22search4 | open-access | yes | assertion | Reactive pattern only; leukemia and CML still require exclusion. |
| 14 | hyperleukocytosis-band | hyperleukocytosis urgent-referral band | extreme leukocytosis | `>100 10*9/L` | all | above | Satty 2023; DOI `10.1182/hematology.2023000464` citeturn11search3turn22search4 | open-access | yes | assertion | Urgency depends on symptoms and cell type, but this threshold is a standard red-flag count. |
| 15 | lymphocytosis-young-child-upper-ri | young-child lymphocytosis above age-banded RI | ALC above CALIPER upper reference limit | `>7.1 10*9/L` | 1-<5 y | above | Tahmasebi 2020; DOI `10.1093/ajcp/aqaa059` citeturn2search1 | open-access | yes | inference | Inferred from the CALIPER upper RI; useful to avoid adult cutoffs in toddlers and preschoolers. |
| 16 | lymphocytosis-school-age-upper-ri | school-age lymphocytosis above age-banded RI | ALC above CALIPER upper reference limit | `>4.1 10*9/L` | 5-<15 y | above | Tahmasebi 2020; DOI `10.1093/ajcp/aqaa059` citeturn2search1 | open-access | yes | inference | Inferred from the CALIPER upper RI. |
| 17 | lymphocytosis-pathologic-child | pathologic lymphocytosis in children | absolute lymphocyte count exceeding pediatric disease-definition threshold | `>10.0 10*9/L` | 2 wk-8/10 y | above | Marionneaux 2020; DOI `10.1016/B978-0-323-53045-3.00035-0` citeturn10search0 | open-access | yes | assertion | Useful counterweight to physiologic childhood lymphocytosis. |
| 18 | eosinophilia-mild | mild eosinophilia | absolute eosinophil count elevation | `0.5-<1.5 10*9/L` | all | between | Ness 2023; DOI `10.1016/j.jpeds.2022.09.048` citeturn24search3 | open-access | yes | assertion | Open-access pediatric cohort severity band. |
| 19 | eosinophilia-moderate | moderate eosinophilia | absolute eosinophil count elevation | `1.5-<4.5 10*9/L` | all | between | Ness 2023; DOI `10.1016/j.jpeds.2022.09.048` citeturn24search3 | open-access | yes | assertion | Open-access pediatric cohort severity band. |
| 20 | eosinophilia-severe | severe eosinophilia | absolute eosinophil count elevation | `>4.5 10*9/L` | all | above | Ness 2023; DOI `10.1016/j.jpeds.2022.09.048` citeturn24search3 | open-access | yes | assertion | Open-access pediatric cohort severity band. |
| 21 | monocytosis-upper-ri-early-childhood | early-childhood monocytosis above age-banded RI | absolute monocyte count above CALIPER upper reference limit | `>1.1 10*9/L` | 0-<5 y | above | Tahmasebi 2020; DOI `10.1093/ajcp/aqaa059` citeturn2search1 | open-access | yes | inference | Inferred from the CALIPER upper RI; analyzer-specific fallback candidate only. |
| 22 | monocytosis-upper-ri-older-child | older-child or adolescent monocytosis above age-banded RI | absolute monocyte count above CALIPER upper reference limit | `>0.8 10*9/L` | 5-<21 y | above | Tahmasebi 2020; DOI `10.1093/ajcp/aqaa059` citeturn2search1 | open-access | yes | inference | Inferred from the CALIPER upper RI; analyzer-specific fallback candidate only. |
| 23 | persistent-monocytosis-clonal-signal | persistent pathologic monocytosis | persistent monocytosis suggesting clonal work-up | `>1.0 10*9/L and >10 % for >3 mo` | all | above | Mangaonkar 2021; DOI `10.1007/s11899-021-00618-4` citeturn23search2 | open-access | yes | assertion | WHO-derived criterion from an open review; not pediatric-specific, so use as review or referral signal only. |
| 24 | mcv-microcytosis-preschool | microcytosis bridge into anemia module | MCV below CALIPER lower reference limit | `<72.8 fL` | 1-<4 y | below | Tahmasebi 2020; DOI `10.1093/ajcp/aqaa059` citeturn7search0 | open-access | yes | inference | Inferred from the CALIPER lower RI; analyzer-specific fallback candidate only. |
| 25 | mcv-macrocytosis-preschool | macrocytosis bridge into anemia module | MCV above CALIPER upper reference limit | `>85.2 fL` | 1-<4 y | above | Tahmasebi 2020; DOI `10.1093/ajcp/aqaa059` citeturn7search0 | open-access | yes | inference | Inferred from the CALIPER upper RI; analyzer-specific fallback candidate only. |
| 26 | mcv-microcytosis-school-age | microcytosis bridge into anemia module | MCV below CALIPER lower reference limit | `<77.4 fL` | 4-<14 y | below | Tahmasebi 2020; DOI `10.1093/ajcp/aqaa059` citeturn7search0 | open-access | yes | inference | Inferred from the CALIPER lower RI; analyzer-specific fallback candidate only. |
| 27 | mcv-macrocytosis-school-age | macrocytosis bridge into anemia module | MCV above CALIPER upper reference limit | `>89.9 fL` | 4-<14 y | above | Tahmasebi 2020; DOI `10.1093/ajcp/aqaa059` citeturn7search0 | open-access | yes | inference | Inferred from the CALIPER upper RI; analyzer-specific fallback candidate only. |

## Source quality and implementation cautions

The **highest-value open numeric sources** in this pass were the **CALIPER 2020 DxH 900 pediatric interval paper**, the **open Brazilian pediatric ITP guideline**, the **open Chinese pediatric ITP adaptation**, the **open ASH pediatric leukocytosis review**, the **open pediatric TTP review**, the **open pediatric DIC review**, the **open Blood Advances severe aplastic anemia consensus**, and the **open Journal of Pediatrics eosinophilia cohort**. Those sources are the main reason most rows above are marked `open-access` and `retrievable_numeric = yes`. citeturn0search0turn21search1turn25search0turn22search4turn13search1turn20search0turn16search0turn24search3

The main design caveat is that many of the CBC-interval rows are **analyzer-specific reference-interval boundaries**, not disease cutoffs. I therefore marked those rows as **`inference`**, because the source directly states the healthy pediatric RI, while the row itself converts that RI boundary into a candidate “high” or “low” interpretation trigger. That is exactly where the existing module’s **local-lab-range precedence** rule should continue to dominate. fileciteturn0file0 citeturn2search1turn7search0

## Gaps and unresolved conflicts

The biggest unresolved source gap remains **CALIPER 2023 Mindray**: it is in the supplied bundle, but its numeric tables were not independently retrievable in an open form during this pass, so I did **not** use it to populate threshold cells. Instead, I used the openly retrievable **CALIPER 2020** values. fileciteturn0file2 citeturn0search0turn7search0

I also did **not** emit a numeric pediatric **peripheral-blast referral** row. I found strong open thresholds for age-banded leukocytosis, leukemoid reaction, and hyperleukocytosis, but I did **not** find a comparably stable, openly retrievable, universally used pediatric CBC-only blast-percentage cutoff that was worth formalizing into a threshold row. That gap is better handled downstream as a **non-numeric smear alert** candidate rather than as a numeric platform-synthesis threshold.

Finally, pediatric eosinophilia has a **minor but real classification conflict** across sources: the open 2023 *Journal of Pediatrics* cohort uses **severe eosinophilia >4.5 ×10*9/L**, while another 2023 pediatric series defines severe as **≥5.0 ×10*9/L**. I retained the **open-access `>4.5 10*9/L`** numbers in the table because they were independently retrievable in full text, but that portability caveat should stay visible in downstream verification. citeturn24search3turn24search0