# Pediatric red-cell interval and discriminator evidence scan

## TL;DR

The strongest openly retrievable interval carrier I found for the analytes your module lacks is the CALIPER DxH 900 study: it provides pediatric reference intervals for **RBC count, hematocrit, MCH, and MCHC** on a named analyzer, with age and sex partitions, in healthy children and adolescents. It is open and numerically retrievable. citeturn25search0turn27search0

On the “definition” question, the most important public-domain exception is **CDC’s 1998 MMWR**, which published pediatric anemia cutoffs for **both hemoglobin and hematocrit**. By contrast, WHO defines anemia by **hemoglobin concentration** on its current public page, and current NHLBI/AAP materials I found do not publish pediatric hematocrit diagnostic cutoffs as the definition of anemia. citeturn47search1turn45search1turn46search1turn45search0

For derived indices, the key negative finding is that the **traditional adult reticulocyte production index is not validated for children**. Bracho and Osorio found **no agreement at any pediatric age** between the traditional adult-normalized RPI and an age-adjusted pediatric RPI, with clinically meaningful disagreement in anemia classification. citeturn39search4turn40view0

For hereditary spherocytosis, **high MCHC can be discriminative in pediatric cohorts**, but the same run also surfaced strong published reasons to fail closed on automated MCHC when there are sample/interference signals: **cold agglutinins, lipemia, hemolysis, cryoglobulins, and very high WBC counts** can all produce spurious CBC relationships. citeturn28search4turn28search7turn28search10turn29search4turn29search0turn30search4turn30search3

## Context and source-selection

I prioritized sources in this order: openly retrievable pediatric interval studies; public-domain federal carriers; then paywalled abstracts only where the abstract itself exposed the exact threshold or performance number. That produced one clear “best” open interval carrier for the missing red-cell analytes: **CALIPER Hematology Reference Standards I** on the **Beckman Coulter DxH 900**, which reports age- and sex-specific pediatric intervals for RBC count, hematocrit, MCH, and MCHC. citeturn25search0turn27search0

I also found a second high-value, independently retrievable open carrier using **NHANES** data and piecewise regression. In the search-accessible excerpt, it exposes pediatric **hematocrit, MCH, MCHC, hemoglobin, and MCV** intervals and is especially valuable if you want an openly retrievable U.S.-based carrier for hemoglobin or MCV that could supersede paywalled rows already in your system. I did **not** use it as the primary Table 1 carrier below because the CALIPER DxH 900 tables exposed the missing analytes more completely in this run. citeturn20search0turn21search0

## Table 1 pediatric red-cell index reference intervals

The table below focuses on analytes your module lacks: **hematocrit, MCHC, MCH, and RBC**. I preserved the source partitions exactly as published. Rows whose published band crosses your operating scope are flagged in `notes` so downstream verification can truncate rather than silently apply the band outside 6 months to <18 years. The source is the CALIPER open-access DxH 900 paper unless otherwise noted. citeturn25search0turn27search0

| row_id | analyte | age_band | sex | lower | upper | unit | method | population | source_citation | access_status | retrievable_numeric | classification | notes |
|---|---|---:|---|---:|---:|---|---|---|---|---|---|---|---|
| rbc-caliper-dxh900-0-lt1-combined | rbc | 0-<1 y | combined | 2.90 | 5.16 | 10*12/L | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling; birth to <21 y | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | Source band includes <6 mo; do not apply below module scope |
| rbc-caliper-dxh900-1-lte14-male | rbc | 1-≤14 y | male | 4.10 | 5.08 | 10*12/L | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | In-scope through <14 y |
| rbc-caliper-dxh900-1-lt14-female | rbc | 1-<14 y | female | 3.94 | 4.97 | 10*12/L | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | In-scope through <14 y |
| rbc-caliper-dxh900-14-lt21-male | rbc | 14-<21 y | male | 4.26 | 5.60 | 10*12/L | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | Source band crosses module upper bound; truncate at <18 y downstream |
| rbc-caliper-dxh900-14-lt21-female | rbc | 14-<21 y | female | 3.95 | 5.13 | 10*12/L | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | Source band crosses module upper bound; truncate at <18 y downstream |
| hct-caliper-dxh900-0-lt1-combined | hematocrit | 0-<1 y | combined | 0.265 | 0.400 | L/L | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling; birth to <21 y | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | Source band includes <6 mo; do not apply below module scope |
| hct-caliper-dxh900-1-lt4-combined | hematocrit | 1-<4 y | combined | 0.304 | 0.398 | L/L | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | In-scope |
| hct-caliper-dxh900-4-lt14-combined | hematocrit | 4-<14 y | combined | 0.335 | 0.418 | L/L | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | In-scope |
| hct-caliper-dxh900-14-lt21-male | hematocrit | 14-<21 y | male | 0.388 | 0.482 | L/L | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | Source band crosses module upper bound; truncate at <18 y downstream |
| hct-caliper-dxh900-14-lt21-female | hematocrit | 14-<21 y | female | 0.344 | 0.437 | L/L | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | Source band crosses module upper bound; truncate at <18 y downstream |
| mch-caliper-dxh900-0-lt1-combined | mch | 0-<1 y | combined | 22.9 | 32.7 | pg | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling; birth to <21 y | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | Source band includes <6 mo; do not apply below module scope |
| mch-caliper-dxh900-1-lt3-combined | mch | 1-<3 y | combined | 22.7 | 29.0 | pg | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | In-scope |
| mch-caliper-dxh900-3-lt6-combined | mch | 3-<6 y | combined | 25.2 | 29.3 | pg | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | In-scope |
| mch-caliper-dxh900-6-lt13-combined | mch | 6-<13 y | combined | 25.4 | 30.8 | pg | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | In-scope |
| mch-caliper-dxh900-13-lt21-combined | mch | 13-<21 y | combined | 25.9 | 32.4 | pg | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | Source band crosses module upper bound; truncate at <18 y downstream |
| mchc-caliper-dxh900-0-lt21-combined | mchc | 0-<21 y | combined | 323 | 350 | g/L | Beckman Coulter DxH 900 | Healthy multiethnic Canadian CALIPER cohort; direct sampling | Tahmasebi 2020; `https://academic.oup.com/ajcp/article/154/3/330/5860205` | open-access | yes | assertion | One source interval across childhood/adolescence; source band includes <6 mo and ≥18 y, so downstream truncation is required |

**High-value companion source not tabulated here:** an open-access NHANES-derived study also exposed independently retrievable pediatric **hematocrit, MCH, MCHC, hemoglobin, and MCV** partitions, which makes it a candidate open supersede carrier for your existing paywalled hemoglobin/MCV rows if you choose to ingest those separately. citeturn20search0turn21search0

## Table 2 discriminators and derived indices

This table keeps one row per source where possible and does **not** reconcile conflicting studies. I treated the special artifacts requested for fail-closed handling as dedicated rows. For formulas whose conventional cutoff is standard but the specific validation abstract did not expose it, I left `threshold` as `unknown` rather than guessing. citeturn36search0turn28search4turn39search4

| row_id | index_or_rule | clinical_question | formula | threshold | direction | age_band | reported_performance | failure_modes | source_citation | access_status | retrievable_numeric | classification | notes |
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
| mchc-hs-michaels-1997 | mchc-hereditary-spherocytosis | Screen children for hereditary spherocytosis | MCHC | >35 g/dL | above | children >12 months | Sensitivity 70%; specificity 86%; AUC 0.86 | Not disease-specific; abstract itself states RDW adds specificity | Michaels 1997; `https://www.sciencedirect.com/science/article/abs/pii/S002234769770283X` | paywalled | yes | assertion | Pediatric cohort: 112 children with HS vs 112 age-matched healthy controls; indices from aperture impedance |
| mchc-rdw-hs-michaels-1997 | mchc-rdw-hereditary-spherocytosis | Combined automated screen for hereditary spherocytosis | MCHC + RDW both elevated | MCHC >35 g/dL and RDW >14 % | above | children >12 months | Combined AUC 0.97; specificity 100%; likelihood ratio infinite | Requires both indices; still a screen, not a diagnostic standard | Michaels 1997; `https://www.sciencedirect.com/science/article/abs/pii/S002234769770283X` | paywalled | yes | assertion | Same pediatric cohort as above |
| mchc-rdw-hs-eberle-2007 | mchc-rdw-hereditary-spherocytosis | Pediatric screening for hereditary spherocytosis | MCHC and RDW | MCHC 34.5 g/dL; RDW 14.5 % | above | age-matched children | Sensitivity 81%; specificity 98.9% | Combination described as “excellent predictor,” but still screening only | Eberle 2007; `https://pubmed.ncbi.nlm.nih.gov/18422060/` | paywalled | yes | assertion | 94 HS patients vs 94 healthy age-matched children; aperture impedance Coulter JT |
| mchc-hs-neonatal-2010 | mchc-hereditary-spherocytosis | Detect hereditary spherocytosis in neonates with hyperbilirubinemia | MCHC | ≥36.0 g/dL | above | neonatal-only | Sensitivity 82%; specificity 98% | Out-of-scope for your module; also DAT-positive hemolysis can elevate MCHC | Christensen 2010; `https://publications.aap.org/pediatrics/article-pdf/125/1/120/1008856/zpe00110000120.pdf` | open-access | yes | assertion | Included because it is a pediatric performance carrier, but neonatal only |
| mchc-artifact-cold-agglutinins | mchc-artifact | Identify spurious automated MCHC elevation from cold agglutinins | CBC internal inconsistency pattern | MCHC >36 % | above | all | unknown | Cold agglutinins can spuriously lower RBC count, raise MCV, reduce apparent Hct, and produce spuriously high MCHC | Solanki 1985; doi:10.1093/ajcp/83.2.218 | paywalled | yes | assertion | Use as fail-closed trigger, not disease discriminator |
| mchc-artifact-lipemia | mchc-artifact | Identify spurious MCHC elevation from lipemia | Photometric Hgb interference causing false MCH/MCHC | >360 g/L | above | all | unknown | Lipemia falsely elevates hemoglobin, MCH, and MCHC; whole-blood lipemia is hard to recognize, so elevated MCHC is a sensitive clue after excluding other causes | Lippi 2023; `https://pmc.ncbi.nlm.nih.gov/articles/PMC10197190/` | open-access | yes | assertion | Review source; threshold described as estimated clue, not disease cutoff |
| mchc-artifact-hemolysis | mchc-artifact | Identify spurious MCHC elevation from hemolysis | CBC affected by RBC lysis | <390 g/L typically suspicious | above | all | unknown | Hemolysis lowers RBC/Hct and can make MCHC spuriously high; reliable reporting may need suppression or comment | Gulati 2022; `https://pmc.ncbi.nlm.nih.gov/articles/PMC9057813/` | open-access | yes | assertion | Review labels mildly elevated MCHC, typically <39 g/dL, as suspicious for hemolysis |
| mchc-artifact-cryoglobulins-hyperwbc | mchc-artifact | Broader fail-closed conditions for spurious red-cell indices | CBC internal inconsistency / abnormal Hb or RBC count | unknown | unknown | all | unknown | Review identifies lipids, agglutinins, cryoglobulins, and elevated WBC counts as causes of abnormal Hb/RBC measurements leading to abnormal calculated indices, with MCHC the most important alerting index | Zandecki 2007; doi:10.1111/j.1365-2257.2006.00871.x | paywalled | yes | assertion | Good umbrella citation for additional fail-closed scenarios |
| mentzer-vehapoglu-2014 | mentzer-index | Differentiate β-thalassemia trait from iron deficiency anemia in children with microcytic anemia | MCV/RBC | <13 1 | below | 1.1-16 y | β-TT: sensitivity 98.7%, specificity 82.3%, PPV 86.3%, NPV 98.2%, Youden 81; IDA: sensitivity 82.3%, specificity 98.7% | None of the indices in the study was completely precise; combined IDA+β-TT cases were excluded | Vehapoglu 2014; doi:10.1155/2014/576738 | open-access | yes | assertion | Best openly retrievable pediatric Mentzer carrier I found |
| mentzer-althumairi-2024 | mentzer-index | Differentiate β-thalassemia trait from iron deficiency anemia among Saudi children with microcytosis | Mentzer index | unknown | unknown | ≤16 y | β-thalassemia trait: sensitivity 74%, specificity 63%; iron deficiency anemia: sensitivity 61%, specificity 36%; NPV for β-TT 98%; PPV for IDA 79% | Study concludes Mentzer index is not highly reliable in this cohort | Althumairi 2024; doi:10.3389/fmed.2024.1361805 | open-access | yes | assertion | Abstract did not expose the exact cutoff used; left threshold unknown rather than assume 13 |
| green-king-vehapoglu-2014 | green-and-king-index | Differentiate β-thalassemia trait from iron deficiency anemia in children | MCV × MCV × RDW / Hb × 100 | <65 1 | below | 1.1-16 y | β-TT: sensitivity 83.1%, specificity 73.5%, PPV 77.6%, NPV 79.3%, Youden 56.6 | Considerable overlap with IDA; not perfectly discriminative | Vehapoglu 2014; doi:10.1155/2014/576738 | open-access | yes | assertion | Pediatric validation present in same cohort as Mentzer |
| rdwi-vehapoglu-2014 | rdwi | Differentiate β-thalassemia trait from iron deficiency anemia in children | MCV × RDW / RBC | <220 1 | below | 1.1-16 y | β-TT: sensitivity 83.1%, specificity 76.4%, PPV 80%, NPV 80%, Youden 59.5 | Moderate false positives and false negatives remain | Vehapoglu 2014; doi:10.1155/2014/576738 | open-access | yes | assertion | Pediatric validation present |
| shine-lal-vehapoglu-2014 | shine-and-lal-index | Differentiate β-thalassemia trait from iron deficiency anemia in children | MCV × MCV × MCH / 100 | <1530 1 | below | 1.1-16 y | β-TT: sensitivity 100%, specificity 10.2%, PPV 55%, NPV 100%, Youden 10.2 | Very poor specificity in this pediatric cohort; high false-positive burden for β-TT screening | Vehapoglu 2014; doi:10.1155/2014/576738 | open-access | yes | assertion | Strong “published failure rate” row |
| corrected-retic-bracho-2020 | corrected-retic | Correct raw reticulocyte percentage for degree of anemia | CRC = reticulocyte (%) × patient hematocrit / normal hematocrit | unknown | unknown | adult-only original; pediatric adaptation discussed | unknown | Adult-normalized CRC uses a normal hematocrit of 45%; pediatric ages have different normal hematocrit values | Bracho 2020; doi:10.1093/ajcp/aqaa020 | open-access | yes | assertion | Formula reproduced openly; original Hillman study was adult-based |
| rpi-traditional-bracho-2020 | reticulocyte-production-index | Assess adequacy of marrow response to anemia | RPI = (reticulocyte (%) × patient hematocrit / normal hematocrit) / maturation time | >3 1 and <2 1 | above / below | adult-only original; widely applied to children but not validated | Traditional interpretation: >3 appropriate marrow response; <2 inadequate response | Bracho found no agreement between traditional RPI and age-adjusted pediatric RPI/A at any pediatric age | Bracho 2020; doi:10.1093/ajcp/aqaa020 | open-access | yes | assertion | Adult thresholds are explicit in the open article, but the same article concludes the traditional RPI is not adequate in pediatrics |
| rpi-age-adjusted-bracho-2020 | reticulocyte-production-index | Pediatric age-adjusted correction for marrow response | RPI/A = (reticulocyte (%) × patient Hct / normal Hct(age)) / maturation time | unknown | unknown | pediatric all ages | No agreement with traditional RPI at any age; up to 24% disagreement for arregenerative classification and up to 15% disagreement for regenerative classification | Misclassification if adult normal Hct of 45% is used in children | Bracho 2020; doi:10.1093/ajcp/aqaa020 | open-access | yes | assertion | Age-specific normal Hct values reported: 6 months-2 y 36%; 2-6 y 37%; 6-12 y 40%; 12-18 y female 41%; 12-18 y male 43%. Maturation-factor breakpoints published by age in the same article |
| hgb-hct-rule-of-three-qc | hgb-hct-rule-of-three | Internal CBC consistency check, not disease definition | Hgb × 3 ≈ Hct; RBC × 3 ≈ Hgb | unknown | between | all | unknown | Deviations occur with microcytosis, macrocytosis, sample problems, or analytical interference; QC/troubleshooting use only was the retrievable use-case I found | Hematology MLS/ASCP teaching page 2026; `https://hematology.mlsascp.com/hematocrit.html` | open-access | yes | annotation | Open retrievable carrier uses the rule as QC/consistency checking rather than as a formal clinical interpretation rule |

## Table 3 the definition question

This is the high-value short answer. The best-supported public-domain “yes” is **CDC 1998**, which published pediatric **hematocrit** cutoffs alongside hemoglobin. WHO’s current public carrier is **hemoglobin-only**. The current NHLBI/AAP materials I found treat hematocrit as part of a CBC or screening workflow, but do **not** publish pediatric hematocrit diagnostic cutoffs as the anemia definition. ASH’s review article is the closest society-adjacent source I found; it says pediatric anemia is defined in practice by low **Hb, Hct, or RBC count** relative to age/sex ranges, but it is not a formal society cutoff table. citeturn47search1turn45search1turn46search1turn45search0turn46search3

| body | defines_by_hct | cutoff_if_any + unit | age_bands | source_citation | access_status | quote_or_locator |
|---|---|---|---|---|---|---|
| WHO | no | none | `<5 y` Hb-only on public carrier | WHO 2026; `https://www.who.int/data/nutrition/nlis/info/anaemia` | public-domain | “Anaemia is defined as a haemoglobin concentration below a specified cut-off point.” |
| CDC | yes | 1-<2 y: `<32.9 %`; 2-<5 y: `<33.0 %`; 5-<8 y: `<34.5 %`; 8-<12 y: `<35.4 %`; male 12-<15 y: `<37.3 %`; male 15-<18 y: `<39.7 %`; female 12-<15 y: `<35.7 %`; female 15-<18 y: `<35.9 %` | 6 months-<18 y, with note that 1-<2 y values can be used for infants 6-12 months | CDC MMWR 1998; `https://www.cdc.gov/mmwr/preview/mmwrhtml/00051880.htm` | public-domain | Table 6: “Maximum hemoglobin concentration and hematocrit values for anemia.” |
| NHLBI / NIH | no | none | pediatric pages discuss age effects but do not publish pediatric Hct anemia cutoffs | NHLBI 2026; `https://www.nhlbi.nih.gov/health/anemia/diagnosis` | public-domain | “Hematocrit levels that are too low may be a sign of anemia.” |
| AAP | no | none | current AAP childhood iron-deficiency screening material accessible in this run uses CBC/ferritin, with hemoglobin as the minimum fallback | AAP News 2026; `https://publications.aap.org/aapnews/news/35298/AAP-report-on-iron-deficiency-includes-expanded` | paywalled | “If a complete blood count and serum ferritin cannot be obtained, at a minimum hemoglobin should be assessed.” |
| ASH | partial | none published in accessible snippet | age- and sex-adjusted ranges; no explicit society cutoff table exposed in accessible snippet | Blood review 2022; `https://ashpublications.org/blood/article-abstract/140/6/571/484178` | paywalled | “In practice, anemia is defined by hemoglobin (Hb), hematocrit, or red blood cell count levels lower than the normal age- and sex-adjusted ranges.” |

## Synthesis and limits

For your missing **input-threshold substrate**, the cleanest open interval insertion point from this run is the **CALIPER DxH 900** carrier for `rbc`, `hematocrit`, `mch`, and `mchc`. It is analyzer-specific, pediatric, age/sex partitioned, and numerically retrievable. The main implementation caveat is not evidentiary but structural: some source bands straddle your scope boundaries, so any downstream use must preserve the source partitions and explicitly truncate outside **6 months to <18 years** rather than silently re-bin or extend them. citeturn25search0turn27search0

For **corrected reticulocyte percentage / RPI**, the strongest answer from this search is negative: adult-normalized RPI is not safe to import unchanged into pediatrics. The open Bracho study provides age-adjusted normal hematocrit denominators and maturation-factor breakpoints, but it simultaneously concludes that the traditional RPI is **not an adequate pediatric tool** because age-adjusted and traditional results do not agree. That means an auto-computed pediatric RPI would still need a cautious verifier stance even if you add hematocrit thresholds. citeturn39search4turn40view0

For **MCHC-driven hereditary-spherocytosis logic**, the evidence supports candidate rows, not an unguarded rule. Pediatric studies do show useful thresholds, but the literature also makes clear that spurious high MCHC can arise from **cold agglutinins, lipemia, hemolysis, cryoglobulins, and hyperleukocytosis**, which means any production logic around MCHC should fail closed when CBC internal consistency breaks or specimen-quality/interference flags are present. citeturn28search4turn28search7turn28search10turn29search4turn29search0turn30search4turn30search3

For the **Hgb↔Hct “rule of three”**, I found openly retrievable laboratory-training/QC usage as an **internal consistency check**, but I did **not** find WHO, CDC, NHLBI, or current AAP guidance endorsing it as a clinical interpretation rule for pediatric anemia. On the evidence located here, it belongs in the “QC/check-for-artifact” bucket, not the “derive patient-facing hematocrit or interpret anemia clinically” bucket. citeturn43search1turn43search3turn45search1turn46search1turn45search0